# Site settings
title: "wely writes"
email: "welyjesch@gmail.com"
description: > # this means to ignore newlines until "baseurl:"
  something might be wrong with you if you're reading this. 
  this guy is like totally boring.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://welyjs.github.io" # the base hostname & protocol for your site
twitter_username: "welyjs"
github_username:  "welyjesch"

# Build settings
markdown: kramdown
